### ISSUE TITLE
Can't figure out how to use loadPaths

### ISSUE THREAD

**Issue by eriklharper** [LPGhatguy/postcss-sassy-import#11]
Here's my postcss config:

```
const path = require('path');

module.exports = {
  plugins: [
    require("postcss-cssnext")({
      features: {
        customProperties: {
          variables: require("./theme/vars.js")
        },
        nesting: false,
      }
    }),
    require("postcss-nested"),
    require("postcss-sassy-import")({
      loadPaths: origin => path.join(process.cwd(), "node_modules")
    })
  ],
};

```
This results in:
```
Failed to compile.

./~/css-loader?{"import":false,"importLoaders":1,"modules":true,"url":false,"localIdentName":"[path][local]_[hash:base64:5]"}!./~/postcss-loader!./theme/Font/styles.css
Module build failed: TypeError: undefined is not a function
    at applyDefaultOptions (/Users/Erik/code/arubanetworks/meridian-react-components/node_modules/postcss-sassy-import/index.js:72:45)
    at /Users/Erik/code/arubanetworks/meridian-react-components/node_modules/postcss-sassy-import/index.js:160:3
    at creator (/Users/Erik/code/arubanetworks/meridian-react-components/node_modules/postcss/lib/postcss.js:150:35)
    at Object.<anonymous> (/Users/Erik/code/arubanetworks/meridian-react-components/postcss.config.js:14:36)
    at Module._compile (module.js:413:34)
    at requireFromString (/Users/Erik/code/arubanetworks/meridian-react-components/node_modules/require-from-string/index.js:27:4)
    at /Users/Erik/code/arubanetworks/meridian-react-components/node_modules/cosmiconfig/lib/loadJs.js:11:15
 @ ./theme/Font/styles.css 4:14-131 13:2-17:4 14:20-137
 @ ./theme/Font/component.js
 @ ./theme/Font/index.js
 @ ./theme/Font/demo.js
 @ ./theme/category.js
 @ ./screens/Demo/screen.js
 @ ./screens/Demo/index.js
 @ ./screens/index.js
 @ multi (webpack)-dev-server/client?http://0.0.0.0:3000 webpack/hot/dev-server react-hot-loader/patch webpack-dev-server/client?http://localhost:3000 webpack/hot/only-dev-server screens/index.js
```
Thoughts?

**Comment by LPGhatguy** [comment]
Oops! This totally looks like the documentation being a bit misleading.

The `loadPaths` value is actually supposed to be an array of functions, not just a function. In your case, this should work:

```js
    require("postcss-sassy-import")({
      loadPaths: [
         origin => path.join(process.cwd(), "node_modules")
      ]
    })
```

I should probably implement some stronger type-checking on the parameters, and also fix that little bit of docuemtnation!

**Comment by eriklharper** [comment]
Thanks, that did end up making it compile for me!  I am noticing, however (and this just may not be a use case you account for) but when I wrap imports in a `:global` it doesn't quite do what I would expect.  Given this code:

```
.default {
  width: 100%;
  height: 100%;

  :global {
    @import "leaflet/dist/leaflet.css";

    .leaflet-container {
      width: 100%;
      height: 100%;
      background-color: transparent;
    }
  }
}
```
I would expect this output:

```
.default {
  width: 100%;
  height: 100%;

  :global {
    /*.... contents of node_modules/leaflet/dist/leaflet.css */

    .leaflet-container {
      width: 100%;
      height: 100%;
      background-color: transparent;
    }
  }
}
```
However, what I see is that the `:global` wrapper is basically removed after it hits `postcss-sassy-import` because the classnames come back hashed from CSS modules instead of preserved as-is.

If I refactor to this (which looks weird, I know), then I can at least keep my overriding styles global, but the imported CSS still is modules-ified because the `:global` block is removed from outside:

```
.default {
  width: 100%;
  height: 100%;

  :global {
    .leaflet-container {
      width: 100%;
      height: 100%;
      background-color: transparent;
    }
  }

  :global {
    @import "leaflet/dist/leaflet.css";
   }
}
```
But, as you can imagine, I shouldn't have to do it that way since ideally the globals come first in the source order, and the overrides come second.  Any thoughts on that use case?  I'm thinking of writing my own plugin to accommodate this...

**Comment by LPGhatguy** [comment]
Curious! I've never used this plugin with either `:global` or any type of CSS modules, so that's not a case I'm very familiar with.

If you figure out how I should be handling that, let me know or submit a pull request and I'll merge it in. I don't do much web development now that I've switched jobs, but I'll still try to get around to it!

**Comment by LPGhatguy** [comment]
I'm going to go ahead and close this issue. I'll open a dedicated issue for CSS Modules support, since that sounds really handy!
