### ISSUE TITLE
Issue with load path

### ISSUE THREAD

**Issue by HashandSalt** [LPGhatguy/postcss-sassy-import#14]
Hi. I've been Googling this for ages but the answer does not seem to anywhere at all. The documentation suggests that you can set the load path. However, I can't seem to make this work through `postcss.config.js`. I'm guessing it should be something like:

```
module.exports = (ctx) => ({
  map: ctx.env === 'development' ? ctx.map : true,
  plugins: {
    'postcss-sassy-import': ctx.env === 'production' ? {
    origin: "node_modules",
    } : true,
    'postcss-unprefix': ctx.env === 'production' ? {} : true,
    'autoprefixer': ctx.env === 'production' ? {} : true,
    'css-mqpacker': ctx.env === 'production' ? {} : true,
    'cssnano': ctx.env === 'production' ? {} : false,
  }
})

```

How do i make it work please? I want to load from the `node_modules` folder and also for files relative, which is the default.

Thanks

**Comment by LPGhatguy** [comment]
The parameter to use is called `loadPaths`. Someone else hit the same issue in #11 -- [here's what I said there.](https://github.com/LPGhatguy/postcss-sassy-import/issues/11#issuecomment-294250295)

In your case, it looks like you'll need something like:

```js
module.exports = (ctx) => ({
  map: ctx.env === 'development' ? ctx.map : true,
  plugins: {
    'postcss-sassy-import': {
      loadPaths: [
        origin => path.join(process.cwd(), 'node_modules'),
        origin => path.dirname(origin)
      ]
    },
    'postcss-unprefix': ctx.env === 'production' ? {} : true,
    'autoprefixer': ctx.env === 'production' ? {} : true,
    'css-mqpacker': ctx.env === 'production' ? {} : true,
    'cssnano': ctx.env === 'production' ? {} : false,
  }
})
```

**Comment by HashandSalt** [comment]
Ok this is almost working now. It's working for css files in the node_modules folder, but not for scss files. Am I misunderstanding something?

I'm importing these files into a scss file and i wanted it to avoid having to put the full path to the files in the node_modules folder in the stylesheet.

If i import normalize.css it works great from the node modules folder.

I have a sass based framework in my node_modules folder, but its not finding the file.

Any idea?

**Comment by HashandSalt** [comment]
Ive just realised the issue. Im such a dofus. It's not a problem with sassy-import. The problem is node-sass cant find the file BEFORE sassy-import does it's thing. If i was importing the sass into a css file that sassy-import then processed, then it would work. Darn it.
