### ISSUE TITLE
confusion with loaders

### ISSUE THREAD

**Issue by timgrafton** [LPGhatguy/postcss-sassy-import#15]
Just wanted to know if I'm using this feature properly? Nothing is being logged to console, so it leads me to believe I'm not.

https://gist.github.com/timgrafton/43c8f01e7f1ffe83ba10c13fff484b02

**Comment by LPGhatguy** [comment]
A loader has to be an object with two fields on it, `test` (a regex), and `method` (the function to use). It looks like you're just passing in a function!

Look at the default loaders located in the source here: https://github.com/LPGhatguy/postcss-sassy-import/blob/master/index.js#L82

The load method is given an object that has both the `path` and `contents` of the file already loaded, so you don't have to handle that.

**Comment by timgrafton** [comment]
Ok thanks.
