### ISSUE TITLE
nested json file

### ISSUE THREAD

**Issue by mmintel** [LPGhatguy/postcss-sassy-import#9]
hi there,

is it possible to import a json file with nested objects? how do I use them in my css?

BR 
Marc

**Comment by LPGhatguy** [comment]
Hey!

Nested JSON objects get imported as [Sass Maps](https://www.viget.com/articles/sass-maps-are-awesome) that are also nested.

**Comment by mmintel** [comment]
I think the problem was that I am using preCSS instead of real sass and they do not support maps

**Comment by LPGhatguy** [comment]
That sounds like it would cause some problems.

Are there any complex data structures supported by preCSS that would work for arbitrary JSON data?

**Comment by LPGhatguy** [comment]
I've opened issue #10 for tracking a potential rewrite of the module that would help address problems like this.
